from autoposemapper.convolutional_autoencoder.models.stacked_convolutional_autoencoder import StackedCE
from autoposemapper.convolutional_autoencoder.models.variational_convolutional_autoencoder import VariationalCE
